[secrets]
SUPABASE_URL = "https://hfwiximcfttzvqzwsatg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmd2l4aW1jZnR0enZxendzYXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTk3NzEsImV4cCI6MjA1NjQ5NTc3MX0.GtEGe2KYbsA_sxPP8Of921SmBSEv6MQ49HB7JNafXLQ"
GROQ_API_KEY = "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"